Update README.md
cbmi-uthsc/webSCAS pull request #7
Opened 2019-03-29 18:23 UTC by pnijhara

Project proposal

2019-03-29 18:43 UTC, duddu-coder commented on README.md
> +Backend of the application will be in django and the project will be completely python based
```suggestion
Backend of the application will be in Flask and the project will be completely python based
```

2019-03-29 18:43 UTC, duddu-coder requested changes
@pnijhara Well, django is a bit heavy for already memory intensive applications. We should consider using Flask for it. 

Have Milk,
Thanks :)

2019-03-29 18:51 UTC, duddu-coder commented
> Project proposal

So this is your project proposal. 
Seems nice to me. I would approve that ;)

2019-03-30 13:29 UTC, pnijhara commented
@akram-mohammed please review it.

2019-05-01 16:25 UTC, merged